<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Affectation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Affectation_model');
    } 

    /*
     * Listing of affectations
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('affectation/index?');
        $config['total_rows'] = $this->Affectation_model->get_all_affectations_count();
        $this->pagination->initialize($config);

        $data['affectations'] = $this->Affectation_model->get_all_affectations($params);
        
        $data['_view'] = 'affectation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new affectation
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'troupe_affecter' => $this->input->post('troupe_affecter'),
				'nomAgent' => $this->input->post('nomAgent'),
				'matriculeAgent' => $this->input->post('matriculeAgent'),
				'telephoneAgent' => $this->input->post('telephoneAgent'),
				'date_affectation' => $this->input->post('date_affectation'),
				'date_created' => date('Y-m-d H:i:s'),
				
            );
            
            $affectation_id = $this->Affectation_model->add_affectation($params);
            redirect('affectation/index');
        }
        else
        {
			$this->load->model('Troupe_model');
			$data['all_troupes'] = $this->Troupe_model->get_all_troupes();
            
            $data['_view'] = 'affectation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a affectation
     */
    function edit($affectation_id)
    {   
        // check if the affectation exists before trying to edit it
        $data['affectation'] = $this->Affectation_model->get_affectation($affectation_id);
        
        if(isset($data['affectation']['affectation_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'troupe_affecter' => $this->input->post('troupe_affecter'),
					'nomAgent' => $this->input->post('nomAgent'),
					'matriculeAgent' => $this->input->post('matriculeAgent'),
					'telephoneAgent' => $this->input->post('telephoneAgent'),
					'date_affectation' => $this->input->post('date_affectation'),
					
					'last_update' => date('Y-m-d H:i:s'),
                );

                $this->Affectation_model->update_affectation($affectation_id,$params);            
                redirect('affectation/index');
            }
            else
            {
				$this->load->model('Troupe_model');
				$data['all_troupes'] = $this->Troupe_model->get_all_troupes();

                $data['_view'] = 'affectation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The affectation you are trying to edit does not exist.');
    } 

    /*
     * Deleting affectation
     */
    function remove($affectation_id)
    {
        $affectation = $this->Affectation_model->get_affectation($affectation_id);

        // check if the affectation exists before trying to delete it
        if(isset($affectation['affectation_id']))
        {
            $this->Affectation_model->delete_affectation($affectation_id);
            redirect('affectation/index');
        }
        else
            show_error('The affectation you are trying to delete does not exist.');
    }
    
}
