<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Demandesactesmariage extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Demandesactesmariage_model');
    } 

    /*
     * Listing of demandesactesmariages
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('demandesactesmariage/index?');
        $config['total_rows'] = $this->Demandesactesmariage_model->get_all_demandesactesmariages_count();
        $this->pagination->initialize($config);

        $data['demandesactesmariages'] = $this->Demandesactesmariage_model->get_all_demandesactesmariages($params);
        
        $data['_view'] = 'demandesactesmariage/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new demandesactesmariage
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nomHomme','NomHomme','required');
		$this->form_validation->set_rules('nomFemme','NomFemme','required');
		$this->form_validation->set_rules('nomTemoin','NomTemoin','required');
		$this->form_validation->set_rules('telephoneCouple','TelephoneCouple','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nomHomme' => $this->input->post('nomHomme'),
				'nomFemme' => $this->input->post('nomFemme'),
				'nomTemoin' => $this->input->post('nomTemoin'),
				'telephoneCouple' => $this->input->post('telephoneCouple'),
				'telephoneTemoin' => $this->input->post('telephoneTemoin'),
				'territoireOrigineCouple' => $this->input->post('territoireOrigineCouple'),
				'villeResidenceCouple' => $this->input->post('villeResidenceCouple'),
				'date_ceremonie' => $this->input->post('date_ceremonie'),
				'heure_ceremonie' => $this->input->post('heure_ceremonie'),
				'frais_ceremonie' => $this->input->post('frais_ceremonie'),
				'date_created' => $this->input->post('date_created'),
				'last_update' => $this->input->post('last_update'),
				'officierCommune' => $this->input->post('officierCommune'),
				'adresseCouple' => $this->input->post('adresseCouple'),
            );
            
            $demandesactesmariage_id = $this->Demandesactesmariage_model->add_demandesactesmariage($params);
            redirect('demandesactesmariage/index');
        }
        else
        {            
            $data['_view'] = 'demandesactesmariage/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a demandesactesmariage
     */
    function edit($demande_id)
    {   
        // check if the demandesactesmariage exists before trying to edit it
        $data['demandesactesmariage'] = $this->Demandesactesmariage_model->get_demandesactesmariage($demande_id);
        
        if(isset($data['demandesactesmariage']['demande_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nomHomme','NomHomme','required');
			$this->form_validation->set_rules('nomFemme','NomFemme','required');
			$this->form_validation->set_rules('nomTemoin','NomTemoin','required');
			$this->form_validation->set_rules('telephoneCouple','TelephoneCouple','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nomHomme' => $this->input->post('nomHomme'),
					'nomFemme' => $this->input->post('nomFemme'),
					'nomTemoin' => $this->input->post('nomTemoin'),
					'telephoneCouple' => $this->input->post('telephoneCouple'),
					'telephoneTemoin' => $this->input->post('telephoneTemoin'),
					'territoireOrigineCouple' => $this->input->post('territoireOrigineCouple'),
					'villeResidenceCouple' => $this->input->post('villeResidenceCouple'),
					'date_ceremonie' => $this->input->post('date_ceremonie'),
					'heure_ceremonie' => $this->input->post('heure_ceremonie'),
					'frais_ceremonie' => $this->input->post('frais_ceremonie'),
					'date_created' => $this->input->post('date_created'),
					'last_update' => $this->input->post('last_update'),
					'officierCommune' => $this->input->post('officierCommune'),
					'adresseCouple' => $this->input->post('adresseCouple'),
                );

                $this->Demandesactesmariage_model->update_demandesactesmariage($demande_id,$params);            
                redirect('demandesactesmariage/index');
            }
            else
            {
                $data['_view'] = 'demandesactesmariage/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The demandesactesmariage you are trying to edit does not exist.');
    } 

    /*
     * Deleting demandesactesmariage
     */
    function remove($demande_id)
    {
        $demandesactesmariage = $this->Demandesactesmariage_model->get_demandesactesmariage($demande_id);

        // check if the demandesactesmariage exists before trying to delete it
        if(isset($demandesactesmariage['demande_id']))
        {
            $this->Demandesactesmariage_model->delete_demandesactesmariage($demande_id);
            redirect('demandesactesmariage/index');
        }
        else
            show_error('The demandesactesmariage you are trying to delete does not exist.');
    }
    
}
