<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class District extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('District_model');
    } 

    /*
     * Listing of districts
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('district/index?');
        $config['total_rows'] = $this->District_model->get_all_districts_count();
        $this->pagination->initialize($config);

        $data['districts'] = $this->District_model->get_all_districts($params);
        
        $data['_view'] = 'district/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new district
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'quartier_sid' => $this->input->post('quartier_sid'),
				'nomDistrict' => $this->input->post('nomDistrict'),
				'nomResponsable' => $this->input->post('nomResponsable'),
				'telephoneResponsable' => $this->input->post('telephoneResponsable'),
				'nombreTroupes' => $this->input->post('nombreTroupes'),
				'date_created' => $this->input->post('date_created'),
				'last_update' => $this->input->post('last_update'),
            );
            
            $district_id = $this->District_model->add_district($params);
            redirect('district/index');
        }
        else
        {
			$this->load->model('Quartier_model');
			$data['all_quartiers'] = $this->Quartier_model->get_all_quartiers();
            
            $data['_view'] = 'district/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a district
     */
    function edit($district_id)
    {   
        // check if the district exists before trying to edit it
        $data['district'] = $this->District_model->get_district($district_id);
        
        if(isset($data['district']['district_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'quartier_sid' => $this->input->post('quartier_sid'),
					'nomDistrict' => $this->input->post('nomDistrict'),
					'nomResponsable' => $this->input->post('nomResponsable'),
					'telephoneResponsable' => $this->input->post('telephoneResponsable'),
					'nombreTroupes' => $this->input->post('nombreTroupes'),
					'date_created' => $this->input->post('date_created'),
					'last_update' => $this->input->post('last_update'),
                );

                $this->District_model->update_district($district_id,$params);            
                redirect('district/index');
            }
            else
            {
				$this->load->model('Quartier_model');
				$data['all_quartiers'] = $this->Quartier_model->get_all_quartiers();

                $data['_view'] = 'district/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The district you are trying to edit does not exist.');
    } 

    /*
     * Deleting district
     */
    function remove($district_id)
    {
        $district = $this->District_model->get_district($district_id);

        // check if the district exists before trying to delete it
        if(isset($district['district_id']))
        {
            $this->District_model->delete_district($district_id);
            redirect('district/index');
        }
        else
            show_error('The district you are trying to delete does not exist.');
    }
    
}
