<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Quartier extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Quartier_model');
    } 

    /*
     * Listing of quartiers
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('quartier/index?');
        $config['total_rows'] = $this->Quartier_model->get_all_quartiers_count();
        $this->pagination->initialize($config);

        $data['quartiers'] = $this->Quartier_model->get_all_quartiers($params);
        
        $data['_view'] = 'quartier/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new quartier
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'commune_sid' => $this->input->post('commune_sid'),
				'nomQuartier' => $this->input->post('nomQuartier'),
				'nomChefQuatier' => $this->input->post('nomChefQuatier'),
				'telephoneChefQuatier' => $this->input->post('telephoneChefQuatier'),
				'nombreCellules' => $this->input->post('nombreCellules'),
				'contactBureauQuartier' => $this->input->post('contactBureauQuartier'),
				'date_created' => $this->input->post('date_created'),
				'last_update' => $this->input->post('last_update'),
				'adresseChefQuatier' => $this->input->post('adresseChefQuatier'),
				'adresseBureauQuartier' => $this->input->post('adresseBureauQuartier'),
            );
            
            $quartier_id = $this->Quartier_model->add_quartier($params);
            redirect('quartier/index');
        }
        else
        {
			$this->load->model('Commune_model');
			$data['all_communes'] = $this->Commune_model->get_all_communes();
            
            $data['_view'] = 'quartier/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a quartier
     */
    function edit($quartier_id)
    {   
        // check if the quartier exists before trying to edit it
        $data['quartier'] = $this->Quartier_model->get_quartier($quartier_id);
        
        if(isset($data['quartier']['quartier_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'commune_sid' => $this->input->post('commune_sid'),
					'nomQuartier' => $this->input->post('nomQuartier'),
					'nomChefQuatier' => $this->input->post('nomChefQuatier'),
					'telephoneChefQuatier' => $this->input->post('telephoneChefQuatier'),
					'nombreCellules' => $this->input->post('nombreCellules'),
					'contactBureauQuartier' => $this->input->post('contactBureauQuartier'),
					'date_created' => $this->input->post('date_created'),
					'last_update' => $this->input->post('last_update'),
					'adresseChefQuatier' => $this->input->post('adresseChefQuatier'),
					'adresseBureauQuartier' => $this->input->post('adresseBureauQuartier'),
                );

                $this->Quartier_model->update_quartier($quartier_id,$params);            
                redirect('quartier/index');
            }
            else
            {
				$this->load->model('Commune_model');
				$data['all_communes'] = $this->Commune_model->get_all_communes();

                $data['_view'] = 'quartier/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The quartier you are trying to edit does not exist.');
    } 

    /*
     * Deleting quartier
     */
    function remove($quartier_id)
    {
        $quartier = $this->Quartier_model->get_quartier($quartier_id);

        // check if the quartier exists before trying to delete it
        if(isset($quartier['quartier_id']))
        {
            $this->Quartier_model->delete_quartier($quartier_id);
            redirect('quartier/index');
        }
        else
            show_error('The quartier you are trying to delete does not exist.');
    }
    
}
