<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Situation extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Situation_model');
    } 

    /*
     * Listing of situations
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('situation/index?');
        $config['total_rows'] = $this->Situation_model->get_all_situations_count();
        $this->pagination->initialize($config);

        $data['situations'] = $this->Situation_model->get_all_situations($params);
        
        $data['_view'] = 'situation/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new situation
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('quartier_sid','Quartier Sid','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'quartier_sid' => $this->input->post('quartier_sid'),
				'intitule' => $this->input->post('intitule'),
				'avenue_sid' => $this->input->post('avenue_sid'),
				'cellule_sid' => $this->input->post('cellule_sid'),
				'date_jour_situation' => $this->input->post('date_jour_situation'),
				'date_created' => $this->input->post('date_created'),
				'last_update' => $this->input->post('last_update'),
				'contenu_situation' => $this->input->post('contenu_situation'),
            );
            
            $situation_id = $this->Situation_model->add_situation($params);
            redirect('situation/index');
        }
        else
        {
			$this->load->model('Quartier_model');
			$data['all_quartiers'] = $this->Quartier_model->get_all_quartiers();
            
            $data['_view'] = 'situation/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a situation
     */
    function edit($situation_id)
    {   
        // check if the situation exists before trying to edit it
        $data['situation'] = $this->Situation_model->get_situation($situation_id);
        
        if(isset($data['situation']['situation_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('quartier_sid','Quartier Sid','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'quartier_sid' => $this->input->post('quartier_sid'),
					'intitule' => $this->input->post('intitule'),
					'avenue_sid' => $this->input->post('avenue_sid'),
					'cellule_sid' => $this->input->post('cellule_sid'),
					'date_jour_situation' => $this->input->post('date_jour_situation'),
					'date_created' => $this->input->post('date_created'),
					'last_update' => $this->input->post('last_update'),
					'contenu_situation' => $this->input->post('contenu_situation'),
                );

                $this->Situation_model->update_situation($situation_id,$params);            
                redirect('situation/index');
            }
            else
            {
				$this->load->model('Quartier_model');
				$data['all_quartiers'] = $this->Quartier_model->get_all_quartiers();

                $data['_view'] = 'situation/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The situation you are trying to edit does not exist.');
    } 

    /*
     * Deleting situation
     */
    function remove($situation_id)
    {
        $situation = $this->Situation_model->get_situation($situation_id);

        // check if the situation exists before trying to delete it
        if(isset($situation['situation_id']))
        {
            $this->Situation_model->delete_situation($situation_id);
            redirect('situation/index');
        }
        else
            show_error('The situation you are trying to delete does not exist.');
    }
    
}
