<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Troupe extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Troupe_model');
    } 

    /*
     * Listing of troupes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('troupe/index?');
        $config['total_rows'] = $this->Troupe_model->get_all_troupes_count();
        $this->pagination->initialize($config);

        $data['troupes'] = $this->Troupe_model->get_all_troupes($params);
        
        $data['_view'] = 'troupe/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new troupe
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('district_sid','District Sid','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'district_sid' => $this->input->post('district_sid'),
				'nomTroupe' => $this->input->post('nomTroupe'),
				'nomResponsable' => $this->input->post('nomResponsable'),
				'telephoneResponsable' => $this->input->post('telephoneResponsable'),
				'date_created' => $this->input->post('date_created'),
				'last_update' => $this->input->post('last_update'),
            );
            
            $troupe_id = $this->Troupe_model->add_troupe($params);
            redirect('troupe/index');
        }
        else
        {
			$this->load->model('District_model');
			$data['all_districts'] = $this->District_model->get_all_districts();
            
            $data['_view'] = 'troupe/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a troupe
     */
    function edit($troupe_id)
    {   
        // check if the troupe exists before trying to edit it
        $data['troupe'] = $this->Troupe_model->get_troupe($troupe_id);
        
        if(isset($data['troupe']['troupe_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('district_sid','District Sid','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'district_sid' => $this->input->post('district_sid'),
					'nomTroupe' => $this->input->post('nomTroupe'),
					'nomResponsable' => $this->input->post('nomResponsable'),
					'telephoneResponsable' => $this->input->post('telephoneResponsable'),
					'date_created' => $this->input->post('date_created'),
					'last_update' => $this->input->post('last_update'),
                );

                $this->Troupe_model->update_troupe($troupe_id,$params);            
                redirect('troupe/index');
            }
            else
            {
				$this->load->model('District_model');
				$data['all_districts'] = $this->District_model->get_all_districts();

                $data['_view'] = 'troupe/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The troupe you are trying to edit does not exist.');
    } 

    /*
     * Deleting troupe
     */
    function remove($troupe_id)
    {
        $troupe = $this->Troupe_model->get_troupe($troupe_id);

        // check if the troupe exists before trying to delete it
        if(isset($troupe['troupe_id']))
        {
            $this->Troupe_model->delete_troupe($troupe_id);
            redirect('troupe/index');
        }
        else
            show_error('The troupe you are trying to delete does not exist.');
    }
    
}
