<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Affectation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get affectation by affectation_id
     */
    function get_affectation($affectation_id)
    {
        return $this->db->get_where('affectations',array('affectation_id'=>$affectation_id))->row_array();
    }
    
    /*
     * Get all affectations count
     */
    function get_all_affectations_count()
    {
        $this->db->from('affectations');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all affectations
     */
    function get_all_affectations($params = array())
    {
        $this->db->order_by('affectation_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('affectations')->result_array();
    }
        
    /*
     * function to add new affectation
     */
    function add_affectation($params)
    {
        $this->db->insert('affectations',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update affectation
     */
    function update_affectation($affectation_id,$params)
    {
        $this->db->where('affectation_id',$affectation_id);
        return $this->db->update('affectations',$params);
    }
    
    /*
     * function to delete affectation
     */
    function delete_affectation($affectation_id)
    {
        return $this->db->delete('affectations',array('affectation_id'=>$affectation_id));
    }
}
