<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cellule_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cellule by cellule_id
     */
    function get_cellule($cellule_id)
    {
        return $this->db->get_where('cellules',array('cellule_id'=>$cellule_id))->row_array();
    }
    
    /*
     * Get all cellules count
     */
    function get_all_cellules_count()
    {
        $this->db->from('cellules');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all cellules
     */
    function get_all_cellules($params = array())
    {
        $this->db->order_by('cellule_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('cellules')->result_array();
    }
        
    /*
     * function to add new cellule
     */
    function add_cellule($params)
    {
        $this->db->insert('cellules',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cellule
     */
    function update_cellule($cellule_id,$params)
    {
        $this->db->where('cellule_id',$cellule_id);
        return $this->db->update('cellules',$params);
    }
    
    /*
     * function to delete cellule
     */
    function delete_cellule($cellule_id)
    {
        return $this->db->delete('cellules',array('cellule_id'=>$cellule_id));
    }
}
