<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class District_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get district by district_id
     */
    function get_district($district_id)
    {
        return $this->db->get_where('districts',array('district_id'=>$district_id))->row_array();
    }
    
    /*
     * Get all districts count
     */
    function get_all_districts_count()
    {
        $this->db->from('districts');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all districts
     */
    function get_all_districts($params = array())
    {
        $this->db->order_by('district_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('districts')->result_array();
    }
        
    /*
     * function to add new district
     */
    function add_district($params)
    {
        $this->db->insert('districts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update district
     */
    function update_district($district_id,$params)
    {
        $this->db->where('district_id',$district_id);
        return $this->db->update('districts',$params);
    }
    
    /*
     * function to delete district
     */
    function delete_district($district_id)
    {
        return $this->db->delete('districts',array('district_id'=>$district_id));
    }
}
