<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Quartier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get quartier by quartier_id
     */
    function get_quartier($quartier_id)
    {
        return $this->db->get_where('quartiers',array('quartier_id'=>$quartier_id))->row_array();
    }
    
    /*
     * Get all quartiers count
     */
    function get_all_quartiers_count()
    {
        $this->db->from('quartiers');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all quartiers
     */
    function get_all_quartiers($params = array())
    {
        $this->db->order_by('quartier_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('quartiers')->result_array();
    }
        
    /*
     * function to add new quartier
     */
    function add_quartier($params)
    {
        $this->db->insert('quartiers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update quartier
     */
    function update_quartier($quartier_id,$params)
    {
        $this->db->where('quartier_id',$quartier_id);
        return $this->db->update('quartiers',$params);
    }
    
    /*
     * function to delete quartier
     */
    function delete_quartier($quartier_id)
    {
        return $this->db->delete('quartiers',array('quartier_id'=>$quartier_id));
    }


    public function search_quartier($query_quartier=null)
    {
        if (!empty($query_quartier)){
            $this->db->like('quartiers.nomQuartier', $query_quartier);
        }
        $this->db->order_by('quartiers.quartier_id', 'DESC');
        $this->db->join('communes', 'communes.commune_id = quartiers.commune_sid');

        $query = $this->db->get('quartiers');

        if ($query) {
            return $query->result();
        } else {
            return false;
        }
    }
}
