<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Situation_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get situation by situation_id
     */
    function get_situation($situation_id)
    {
        return $this->db->get_where('situations',array('situation_id'=>$situation_id))->row_array();
    }
    
    /*
     * Get all situations count
     */
    function get_all_situations_count()
    {
        $this->db->from('situations');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all situations
     */
    function get_all_situations($params = array())
    {
        $this->db->order_by('situation_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('situations')->result_array();
    }
        
    /*
     * function to add new situation
     */
    function add_situation($params)
    {
        $this->db->insert('situations',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update situation
     */
    function update_situation($situation_id,$params)
    {
        $this->db->where('situation_id',$situation_id);
        return $this->db->update('situations',$params);
    }
    
    /*
     * function to delete situation
     */
    function delete_situation($situation_id)
    {
        return $this->db->delete('situations',array('situation_id'=>$situation_id));
    }
}
