<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Troupe_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get troupe by troupe_id
     */
    function get_troupe($troupe_id)
    {
        return $this->db->get_where('troupes',array('troupe_id'=>$troupe_id))->row_array();
    }
    
    /*
     * Get all troupes count
     */
    function get_all_troupes_count()
    {
        $this->db->from('troupes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all troupes
     */
    function get_all_troupes($params = array())
    {
        $this->db->order_by('troupe_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('troupes')->result_array();
    }
        
    /*
     * function to add new troupe
     */
    function add_troupe($params)
    {
        $this->db->insert('troupes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update troupe
     */
    function update_troupe($troupe_id,$params)
    {
        $this->db->where('troupe_id',$troupe_id);
        return $this->db->update('troupes',$params);
    }
    
    /*
     * function to delete troupe
     */
    function delete_troupe($troupe_id)
    {
        return $this->db->delete('troupes',array('troupe_id'=>$troupe_id));
    }
}
