<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_am_user by id_asset
     */
    function get_tb_am_user($id_asset)
    {
        return $this->db->get_where('tb_im_users',array('id_asset'=>$id_asset))->row_array();
    }
    
    /*
     * Get all tb_am_users count
     */
    function get_all_tb_am_users_count()
    {
        $this->db->from('tb_im_users');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_am_users
     */
    function get_all_tb_am_users($params = array())
    {
        $this->db->order_by('id_asset', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_im_users')->result_array();
    }
        
    /*
     * function to add new tb_am_user
     */
    function add_tb_am_user($params)
    {
        $this->db->insert('tb_im_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_am_user
     */
    function update_tb_am_user($id_asset,$params)
    {
        $this->db->where('id_asset',$id_asset);
        return $this->db->update('tb_im_users',$params);
    }
    
    /*
     * function to delete tb_am_user
     */
    function delete_tb_am_user($id_asset)
    {
        return $this->db->delete('tb_im_users',array('id_asset'=>$id_asset));
    }
}
